# Ansible inventory — generated by Terraform. Do not edit manually.

%{ if ssh_private_key_file != "" ~}
[all:vars]
ansible_ssh_private_key_file=${ssh_private_key_file}

%{ endif ~}
%{ if parent_group != "" ~}
[${parent_group}:children]
%{ for group_name in group_names ~}
${group_name}
%{ endfor ~}

%{ endif ~}
%{ for group_name, hosts in groups ~}
[${group_name}]
%{ for host in hosts ~}
%{ if host.ansible_host != "" ~}
${host.name} ansible_host=${host.ansible_host} ansible_user=${host.ansible_user}
%{ endif ~}
%{ endfor ~}

%{ endfor ~}
