# Ansible inventory — generated by Terraform. Do not edit manually.

%{ if ssh_private_key_file != "" ~}
[all:vars]
ansible_ssh_private_key_file=${ssh_private_key_file}

%{ endif ~}
%{ for parent, children in hierarchy ~}
[${parent}:children]
%{ for child in children ~}
${child}
%{ endfor ~}

%{ endfor ~}
%{ for group_name, hosts in groups ~}
[${group_name}]
%{ for host in hosts ~}
%{ if host.ansible_host != "" ~}
${host.name} ansible_host=${host.ansible_host} ansible_user=${host.ansible_user}
%{ endif ~}
%{ endfor ~}

%{ endfor ~}
